server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: school-records-backend
  datasource:
    url: jdbc:postgresql://db:5432/school_records
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
